
version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - POSTGRES_ENABLED=${POSTGRES_ENABLED:-true} # Set to false to disable, true to enable PostgreSQL usage
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=financeapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./data:/data
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=financeapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # The db service can be commented out to run app without a database.

volumes:
  postgres_data:
