
version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - POSTGRES_ENABLED=${POSTGRES_ENABLED:-true} # Set to false to disable, true to enable PostgreSQL usage
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=financeapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - ./data:/data
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=financeapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # The db service can be commented out to run app without a database.

volumes:
  postgres_data:
